# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 08:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id_role', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'eff_role',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id_userrole', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.ForeignKey(db_column='id_role', on_delete=django.db.models.deletion.CASCADE, to='framework.Role')),
                ('user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'eff_userrole',
            },
        ),
    ]
